runtime: python27
threadsafe: no
api_version: 1

# Try to limit costs from F(rontend) instances
automatic_scaling:
  max_instances: 1

handlers:

- url: /.*
  script: comments.py

#- url: /(comments\.py)
#  static_files: \1
#  upload: comments\.py
